### ISSUE TITLE
ScheduledJob in get  remote time has something wrong...

### ISSUE THREAD

**Issue by hanc00l** [mez-0/MoveScheduler#1]
This is my test:

> PS D:\MoveScheduler\MoveScheduler\bin\Release> ./MoveScheduler.exe -m SchedulerAPI -t 172.16.80.133 -d win-05rdrsb4ebp -u administrator -p abcd@1234 -c whoami
[*] Connecting to: 172.16.80.133
[*] Authenticating as: win-05rdrsb4ebp\administrator:abcd@1234
[*] Command: whoami
[*] Arguments:
[*] Creating new task: a91af468
[*] Local Time is: 2020/9/2 13:50:38	<-- today now!
[*] Remote Time is: 2020/2/9 13:50:38	<-- here:get remote time wrong
[*] Time to add is: 0
[*] Remote start time is 0 minute(s) from now: 2020/2/9 13:50:38
[*] Will trigger at: 2020/2/9 13:50:38
[*] Running with highest privs!
[*] Adding to root folder...
[+] Task: 'a91af468' User: 'win-05rdrsb4ebp\administrator' Enabled: True Next Run: 0001/1/1

So,I found the code in Utils.cs:
```csharp
SelectQuery timeQuery = new SelectQuery(@"SELECT * FROM Win32_LocalTime");
ManagementObjectSearcher timeQuerySearcher = new ManagementObjectSearcher(managementScope, timeQuery);
try
{
    foreach (ManagementObject mo in timeQuerySearcher.Get())
    {
        //String t = $"{mo["Day"]}/{mo["Month"]}/{mo["Year"]} {mo["Hour"]}:{mo["Minute"]}:{mo["Second"]}";  <--origin
        String t = $"{mo["Month"]}/{mo["Day"]}/{mo["Year"]} {mo["Hour"]}:{mo["Minute"]}:{mo["Second"]}";  // <--  I changed
        r = DateTime.Parse(t);
        return r;
    }
}
catch (Exception e)
{
    Logger.Print(Logger.STATUS.INFO, "Failed to get remote DateTime, using local system time.");
    r = DateTime.Now;
    return r;
}
```

I found the reference:

> A string that includes the date and time along with time zone offset information; for example:
"03/01/2009 05:42:00 -5:00" <--- "Month/Day/Year ..."

[https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=netcore-3.1#StringToParse](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.parse?view=netcore-3.1#StringToParse)

Now This is the next test:

> PS D:\MoveScheduler\MoveScheduler\bin\Release> ./MoveScheduler.exe -m SchedulerAPI -t 172.16.80.133 -d win-05rdrsb4ebp -u administrator -p abcd@1234 -c whoami --time 1
[*] Connecting to: 172.16.80.133
[*] Authenticating as: win-05rdrsb4ebp\administrator:abcd@1234
[*] Command: whoami
[*] Arguments:
[*] Creating new task: 0c92ae86
[*] Local Time is: 2020/9/2 14:02:10
[*] Remote Time is: 2020/9/2 14:02:10  <--correct time
[*] Time to add is: 1
[*] Remote start time is 1 minute(s) from now: 2020/9/2 14:03:10
[*] Will trigger at: 2020/9/2 14:03:10
[*] Running with highest privs!
[*] Adding to root folder...
[+] Task: '0c92ae86' User: 'win-05rdrsb4ebp\administrator' Enabled: True Next Run: 2020/9/2 14:03:10
PS D:\MoveScheduler\MoveScheduler\bin\Release>

Sorry my poor English :)

**Comment by mez-0** [comment]
Hey @hanc00l, I am not actively maintaining this tool. If you have fixed it, you could put in a PR :)

Also, when testing, I was always adding a 2 or 3 minute delay to cover for any time disparity.

**Comment by mez-0** [comment]
@hanc00l, just checked in my lab. its the correct time? Will mark as closed.
